### ISSUE TITLE
`hvac_modes` attribute incorrectly displayed by template

### ISSUE THREAD

**Issue by marco-hacs** [oyvindwe/connectlife-ha#148]
I have noticed that the attributes are displayed incorrectly when using templates despite the fact that they are correctly presented as entities. Normal behaviour should return a list.

![image](https://github.com/user-attachments/assets/a0483436-af39-4014-9fc9-443853f449b3)
![image](https://github.com/user-attachments/assets/d14bccb4-8f47-443c-8f43-cdeae7b578dd)

**Comment by marco-hacs** [comment]
RESOLVED: need to force .value for HVACMode.OFF and hvac_modes.append(mode).
 
I didn't make a pr because I'm not very familiar with github. hope I've been of some help though

![image](https://github.com/user-attachments/assets/6e8cad00-945f-4702-b277-cba1eb2f7dec)

![image](https://github.com/user-attachments/assets/2d8db2fb-de4f-403d-97e5-d6f569430890)

**Comment by oyvindwe** [comment]
This is helpful! Even better than screen shots are code samples in markdown code blocks, but I can fix this. :)

Does this issue only apply to the `HVACMode` attribute?

**Comment by oyvindwe** [comment]
@marco-hacs Investigating this, I think the problem is with your template. `hvac_modes` as strings is only supported for backwards compatibility. See https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/__init__.py#L467-L475 and [HVAC modes](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes)

If you use e.g. the `join` filter, the modes are nicely formatted:
```
HVAC modes: {{ state_attr("climate.air_conditioner_006_200", "hvac_modes")|join(",")}}
```
